### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by simon-clematide** [eske/word2vecpp-legacy#1]
The sample commands 

```
wget http://www.statmt.org/wmt14/training-parallel-nc-v9.tgz -P data
tar xzf data/de-en.tgz -C data
```

are inconsistent. http://www.statmt.org/wmt14/training-parallel-nc-v9.tgz is the news corpus, not the Europarl.

The script

```
scripts/prepare.py
```

seems to have changed into prepare-data.py , but doesn't expect the same arguments.

**Comment by alex-berard** [comment]
Thank you for your comments. You're right, the documentation was outdated and inconsistent.

I've just changed it. Please tell me if you see any other problem.
