### ISSUE TITLE
Reference Performance

### ISSUE THREAD

**Issue by simon-clematide** [eske/word2vecpp-legacy#4]
Using all test command from the documentation, I achieve the following numbers on a Debian 8 x86_64 machine. It might be helpful to have reference information.

```
Vocabulary size: 25298
Embeddings size: 100
capital-common-countries:
    accuracy: -nan%
capital-world:
    accuracy: -nan%
city-in-state:
    accuracy: -nan%
currency:
    accuracy: -nan%
family:
    accuracy: 33.3%
gram1-adjective-to-adverb:
    accuracy: 1.85%
gram2-opposite:
    accuracy: 4.99%
gram3-comparative:
    accuracy: 27.5%
gram4-superlative:
    accuracy: 10.5%
gram5-present-participle:
    accuracy: 15.4%
gram6-nationality-adjective:
    accuracy: -nan%
gram7-past-tense:
    accuracy: 9.46%
gram8-plural:
    accuracy: 4.15%
gram9-plural-verbs:
    accuracy: 18.9%
Total accuracy: 13.2%
Syntactic accuracy: 12.8%, Semantic accuracy: 33.3%
Questions seen: 6792/19544, 34.8%
```

This should be an enhancement, not a bug issue.

**Comment by alex-berard** [comment]
Hi Simon,

Thanks for your input, that's a good idea, I will add results to the README.

Results seem to vary a lot though. I tried running it myself, and I obtained 14.8% syntactic accuracy, and 36.4% semantic accuracy.

For the monolingual model trained on a parallel corpus (which is supposed to be what you get if you follow the steps), I get 25.4% and 47.7%.

**Comment by simon-clematide** [comment]
My results vary as well for each run by few percentage points.
