### ISSUE TITLE
Python Example uses wrong names for classes

### ISSUE THREAD

**Issue by simon-clematide** [eske/word2vecpp-legacy#5]
The Python example uses BilingualModel and MonolingualModel, but it should be BiModel and MonoModel.

**Comment by alex-berard** [comment]
Hello Simon,

Actually, the Python wrapper has changed a little bit. It now uses Cython, instead of C extensions. It's much clearer, and it now includes a lot more features.
I changed the class names from MonoModel and to MonolingualModel, and BiModel to BilingualModel to match with the C++ names.

**Comment by simon-clematide** [comment]
Ok, I probably still had an older versions installed in my path.
